<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\SalesPortal.Application\SalesPortal.Application.csproj" />
    <ProjectReference Include="..\SalesPortal.Infrastructure\SalesPortal.Infrastructure.csproj" />
    <ProjectReference Include="..\SalesPortal.Shared\SalesPortal.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.3.10" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
