<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.10" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SalesPortal.Application\SalesPortal.Application.csproj" />
    <ProjectReference Include="..\SalesPortal.Domain\SalesPortal.Domain.csproj" />
    <ProjectReference Include="..\SalesPortal.Shared\SalesPortal.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Sap.Data.Hana.v4.5">
      <HintPath>..\SalesPortal.Shared\Dependencies\Sap.Data.Hana.v4.5.dll</HintPath>
    </Reference>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
